name: Autobuild Release
description: Publish autobuild artifacts to GitHub releases

inputs:
  public:
    type: boolean
    description: Whether these artifacts are public or not
    default: true 
  upload-to:
    type: string
    description: "The locations to upload the artifacts to. Defaults to github releases."
    default: github-release://
  token:
    description: "Authorized Github Personal Acess Token. Defaults to GITHUB_TOKEN"
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
